In [137]:
import pandas

In [138]:
file_name = "./datasets.csv"

In [139]:
standings_data_frame = pandas.read_csv(file_name)
standings_data_frame = standings_data_frame.sort_values(
    by=["country", "competition_tier", "competition", "season"]
)
standings_data_frame.to_csv(file_name, index=False)
standings_data_frame

,country,competition_tier,competition,season,champion,champion_former,champion_point,runner_up,runner_up_former,runner_up_point,third_place,third_place_former,third_place_point,fourth_place,fourth_place_point,teams,rounds
0,England,1,Premier League,1992-1993,Manchester United,NaN,NaN,Aston Villa,NaN,NaN,Norwich City,NaN,NaN,Blackburn Rovers,NaN,NaN,NaN
1,England,1,Premier League,1993-1994,Manchester United,NaN,NaN,Blackburn Rovers,NaN,NaN,Newcastle United,NaN,NaN,Arsenal,NaN,NaN,NaN
2,England,1,Premier League,1994-1995,Blackburn Rovers,NaN,NaN,Manchester United,NaN,NaN,Nottingham Forrest,NaN,NaN,Liverpool,NaN,NaN,NaN
3,England,1,Premier League,1995-1996,Manchester United,NaN,NaN,Newcastle United,NaN,NaN,Liverpool,NaN,NaN,Aston Villa,NaN,NaN,NaN
4,England,1,Premier League,1996-1997,Manchester United,NaN,NaN,Newcastle United,NaN,NaN,Arsenal,NaN,NaN,Liverpool,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,United States,1,Major League Soccer,2018,New York Red Bulls,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,United States,1,Major League Soccer,2019,Los Angeles FC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,United States,1,Major League Soccer,2020,Philadelphia Union,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,United States,1,Major League Soccer,2021,New England Revolution,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,United States,1,Major League Soccer,2022,Los Angeles FC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
competitions = standings_data_frame["competition"].unique()
competitions

array(['Premier League', 'English Football League - Championship',
       'English Football League - League One',
       'English Football League - League Two', 'National League',
       'National League North', 'National League South', 'Ligue 1',
       'Bundesliga', 'Seria A', 'J1 League', 'K League 1', 'K League 2',
       'Eredivisie', 'Primeira Liga', 'Singapore Premier League',
       'La Liga', 'Major League Soccer'], dtype=object)

## Premier League

In [141]:
premier_league_data_frame = standings_data_frame[
    standings_data_frame["competition"] == "Premier League"
]
premier_league_data_frame

,country,competition_tier,competition,season,champion,champion_former,champion_point,runner_up,runner_up_former,runner_up_point,third_place,third_place_former,third_place_point,fourth_place,fourth_place_point,teams,rounds
0,England,1,Premier League,1992-1993,Manchester United,NaN,NaN,Aston Villa,NaN,NaN,Norwich City,NaN,NaN,Blackburn Rovers,NaN,NaN,NaN
1,England,1,Premier League,1993-1994,Manchester United,NaN,NaN,Blackburn Rovers,NaN,NaN,Newcastle United,NaN,NaN,Arsenal,NaN,NaN,NaN
2,England,1,Premier League,1994-1995,Blackburn Rovers,NaN,NaN,Manchester United,NaN,NaN,Nottingham Forrest,NaN,NaN,Liverpool,NaN,NaN,NaN
3,England,1,Premier League,1995-1996,Manchester United,NaN,NaN,Newcastle United,NaN,NaN,Liverpool,NaN,NaN,Aston Villa,NaN,NaN,NaN
4,England,1,Premier League,1996-1997,Manchester United,NaN,NaN,Newcastle United,NaN,NaN,Arsenal,NaN,NaN,Liverpool,NaN,NaN,NaN
5,England,1,Premier League,1997-1998,Arsenal,NaN,NaN,Manchester United,NaN,NaN,Liverpool,NaN,NaN,Chelsea,NaN,NaN,NaN
6,England,1,Premier League,1998-1999,Manchester United,NaN,NaN,Arsenal,NaN,NaN,Chelsea,NaN,NaN,Leeds United,NaN,NaN,NaN
7,England,1,Premier League,1999-2000,Manchester United,NaN,NaN,Arsenal,NaN,NaN,Leeds United,NaN,NaN,Liverpool,NaN,NaN,NaN
8,England,1,Premier League,2000-2001,Manchester United,NaN,NaN,Arsenal,NaN,NaN,Liverpool,NaN,NaN,Leeds United,NaN,NaN,NaN
9,England,1,Premier League,2001-2002,Arsenal,NaN,NaN,Liverpool,NaN,NaN,Manchester United,NaN,NaN,Newcastle United,NaN,NaN,NaN
10,England,1,Premier League,2002-2003,Manchester United,NaN,NaN,Arsenal,NaN,NaN,Newcastle United,NaN,NaN,Chelsea,NaN,NaN,NaN
11,England,1,Premier League,2003-2004,Arsenal,NaN,NaN,Chelsea,NaN,NaN,Manchester United,NaN,NaN,Liverpool,NaN,NaN,NaN
12,England,1,Premier League,2004-2005,Chelsea,NaN,NaN,Arsenal,NaN,NaN,Manchester United,NaN,NaN,Everton,NaN,NaN,NaN
13,England,1,Premier League,2005-2006,Chelsea,NaN,NaN,Manchester United,NaN,NaN,Liverpool,NaN,NaN,Arsenal,NaN,NaN,NaN
14,England,1,Premier League,2006-2007,Manchester United,NaN,NaN,Chelsea,NaN,NaN,Liverpool,NaN,NaN,Arsenal,NaN,NaN,NaN
15,England,1,Premier League,2007-2008,Manchester United,NaN,NaN,Chelsea,NaN,NaN,Arsenal,NaN,NaN,Liverpool,NaN,NaN,NaN
16,England,1,Premier League,2008-2009,Manchester United,NaN,NaN,Liverpool,NaN,NaN,Chelsea,NaN,NaN,Arsenal,NaN,NaN,NaN
17,England,1,Premier League,2009-2010,Chelsea,NaN,NaN,Manchester United,NaN,NaN,Arsenal,NaN,NaN,Tottenham Hotspur,NaN,NaN,NaN
18,England,1,Premier League,2010-2011,Manchester United,NaN,NaN,Chelsea,NaN,NaN,Arsenal,NaN,NaN,Manchester City,NaN,NaN,NaN
19,England,1,Premier League,2011-2012,Manchester City,NaN,NaN,Manchester United,NaN,NaN,NaN,NaN,NaN,Chelsea,NaN,NaN,NaN
20,England,1,Premier League,2012-2013,Manchester United,NaN,NaN,Manchester City,NaN,NaN,Chelsea,NaN,NaN,Arsenal,NaN,NaN,NaN
21,England,1,Premier League,2013-2014,Manchester City,NaN,NaN,Liverpool,NaN,NaN,Chelsea,NaN,NaN,Arsenal,NaN,NaN,NaN
22,England,1,Premier League,2014-2015,Chelsea,NaN,NaN,Manchester City,NaN,NaN,Arsenal,NaN,NaN,Manchester United,NaN,NaN,NaN
23,England,1,Premier League,2015-2016,Leicester City,NaN,NaN,Arsenal,NaN,NaN,Tottenham Hotspur,NaN,NaN,Manchester City,NaN,NaN,NaN
24,England,1,Premier League,2016-2017,Chelsea,NaN,NaN,Tottenham Hotspur,NaN,NaN,Manchester City,NaN,NaN,Liverpool,NaN,NaN,NaN
25,England,1,Premier League,2017-2018,Manchester City,NaN,NaN,Manchester United,NaN,NaN,Tottenham Hotspur,NaN,NaN,Liverpool,NaN,NaN,NaN
26,England,1,Premier League,2018-2019,Manchester City,NaN,NaN,Liverpool,NaN,NaN,Chelsea,NaN,NaN,Tottenham Hotspur,NaN,NaN,NaN
27,England,1,Premier League,2019-2020,Liverpool,NaN,NaN,Manchester City,NaN,NaN,Manchester United,NaN,NaN,Chelsea,NaN,NaN,NaN
28,England,1,Premier League,2020-2021,Manchester City,NaN,NaN,Manchester United,NaN,NaN,Liverpool,NaN,NaN,Chelsea,NaN,NaN,NaN
29,England,1,Premier League,2021-2022,Manchester City,NaN,NaN,Liverpool,NaN,NaN,Chelsea,NaN,NaN,Tottenham Hotspur,NaN,NaN,NaN
30,England,1,Premier League,2022-2023,Manchester City,NaN,NaN,Arsenal,NaN,NaN,Manchester United,NaN,NaN,Newcastle United,NaN,NaN,NaN

In [142]:
champions = premier_league_data_frame["champion"].value_counts()
champions

champion
Manchester United    13
Manchester City       7
Chelsea               5
Arsenal               3
Blackburn Rovers      1
Leicester City        1
Liverpool             1
Name: count, dtype: int64

In [143]:
runners_up = premier_league_data_frame["runner_up"].value_counts()
runners_up

runner_up
Manchester United    7
Arsenal              7
Liverpool            5
Chelsea              4
Manchester City      3
Newcastle United     2
Aston Villa          1
Blackburn Rovers     1
Tottenham Hotspur    1
Name: count, dtype: int64

In [144]:
third_places = premier_league_data_frame["third_place"].value_counts()
third_places

third_place
Liverpool             6
Chelsea               6
Arsenal               5
Manchester United     5
Newcastle United      2
Tottenham Hotspur     2
Norwich City          1
Nottingham Forrest    1
Leeds United          1
Manchester City       1
Name: count, dtype: int64

In [145]:
fourth_places = premier_league_data_frame["fourth_place"].value_counts()
fourth_places

fourth_place
Liverpool            7
Arsenal              6
Chelsea              5
Tottenham Hotspur    3
Leeds United         2
Newcastle United     2
Manchester City      2
Blackburn Rovers     1
Aston Villa          1
Everton              1
Manchester United    1
Name: count, dtype: int64